#!/bin/sh
#
# @name Vitesse V2
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 aileron
# @output MAIN2 aileron
# @output MAIN3 elevator
# @output MAIN4 rudder
# @output MAIN5 throttle
# @output MAIN6 flaps
# @output MAIN7 flaps
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Christopher Ruwisch <christopher.ruwisch@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_AIRSPD_MIN 10
param set-default FW_AIRSPD_MAX 30
param set-default FW_AIRSPD_TRIM 18

param set-default PWM_MAIN_DISARM 1000


set MIXER AAERTFF


# Rate must be set by group (see pwm info).
# Throttle is in the same group as servos.
set PWM_OUT 6
